const medicalRecords = [
  {
    patientId: "patient1",
    doctorId: "doctor1",
    diagnosis: "Flu",
    prescription: "Rest and hydration",
    date: "2024-08-01",
  },
  {
    patientId: "patient1",
    doctorId: "doctor2",
    diagnosis: "Headache",
    prescription: "Ibuprofen",
    date: "2024-08-15",
  },
  {
    patientId: "patient1",
    doctorId: "doctor1",
    diagnosis: "Back Pain",
    prescription: "Physical therapy",
    date: "2024-08-20",
  },
  {
    patientId: "patient2",
    doctorId: "doctor2",
    diagnosis: "Allergy",
    prescription: "Antihistamines",
    date: "2024-07-15",
  },
  {
    patientId: "patient2",
    doctorId: "doctor1",
    diagnosis: "Anxiety",
    prescription: "Counseling",
    date: "2024-08-10",
  },
  {
    patientId: "patient2",
    doctorId: "doctor2",
    diagnosis: "Sprained Ankle",
    prescription: "RICE method",
    date: "2024-09-05",
  },
  {
    patientId: "patient3",
    doctorId: "doctor1",
    diagnosis: "High Blood Pressure",
    prescription: "Medication",
    date: "2024-07-20",
  },
  {
    patientId: "patient3",
    doctorId: "doctor2",
    diagnosis: "Chest Pain",
    prescription: "Cardiac evaluation",
    date: "2024-08-25",
  },
  {
    patientId: "patient3",
    doctorId: "doctor1",
    diagnosis: "Routine Checkup",
    prescription: "Follow-up in 6 months",
    date: "2024-09-10",
  },
  {
    patientId: "patient4",
    doctorId: "doctor2",
    diagnosis: "Stomach Ache",
    prescription: "Antacids",
    date: "2024-08-05",
  },
  {
    patientId: "patient4",
    doctorId: "doctor1",
    diagnosis: "Skin Rash",
    prescription: "Topical cream",
    date: "2024-08-15",
  },
  {
    patientId: "patient4",
    doctorId: "doctor2",
    diagnosis: "Routine Checkup",
    prescription: "Healthy diet",
    date: "2024-09-01",
  },
  {
    patientId: "patient5",
    doctorId: "doctor1",
    diagnosis: "Fever",
    prescription: "Paracetamol",
    date: "2024-08-10",
  },
  {
    patientId: "patient5",
    doctorId: "doctor2",
    diagnosis: "Cold",
    prescription: "Rest and fluids",
    date: "2024-08-20",
  },
  {
    patientId: "patient5",
    doctorId: "doctor1",
    diagnosis: "Allergy Test",
    prescription: "Blood test",
    date: "2024-09-15",
  },
  {
    patientId: "patient6",
    doctorId: "doctor1",
    diagnosis: "Depression",
    prescription: "Therapy sessions",
    date: "2024-08-01",
  },
  {
    patientId: "patient6",
    doctorId: "doctor2",
    diagnosis: "Routine Checkup",
    prescription: "Regular exercise",
    date: "2024-08-10",
  },
  {
    patientId: "patient6",
    doctorId: "doctor1",
    diagnosis: "Fatigue",
    prescription: "Blood tests",
    date: "2024-09-05",
  },
  {
    patientId: "patient7",
    doctorId: "doctor2",
    diagnosis: "Knee Pain",
    prescription: "Physical therapy",
    date: "2024-08-10",
  },
  {
    patientId: "patient7",
    doctorId: "doctor1",
    diagnosis: "Routine Checkup",
    prescription: "Follow-up in 3 months",
    date: "2024-08-25",
  },
  {
    patientId: "patient7",
    doctorId: "doctor2",
    diagnosis: "Cold",
    prescription: "Rest and hydration",
    date: "2024-09-10",
  },
  {
    patientId: "patient8",
    doctorId: "doctor1",
    diagnosis: "Anxiety",
    prescription: "Medication",
    date: "2024-07-20",
  },
  {
    patientId: "patient8",
    doctorId: "doctor2",
    diagnosis: "Routine Checkup",
    prescription: "Regular exercise",
    date: "2024-08-15",
  },
  {
    patientId: "patient8",
    doctorId: "doctor1",
    diagnosis: "Fatigue",
    prescription: "Blood tests",
    date: "2024-09-01",
  },
  {
    patientId: "patient9",
    doctorId: "doctor2",
    diagnosis: "Flu",
    prescription: "Rest and fluids",
    date: "2024-07-15",
  },
  {
    patientId: "patient9",
    doctorId: "doctor1",
    diagnosis: "Back Pain",
    prescription: "Physical therapy",
    date: "2024-08-20",
  },
  {
    patientId: "patient9",
    doctorId: "doctor2",
    diagnosis: "Routine Checkup",
    prescription: "Annual checkup",
    date: "2024-09-10",
  },
  {
    patientId: "patient10",
    doctorId: "doctor1",
    diagnosis: "Migraine",
    prescription: "Medication",
    date: "2024-07-10",
  },
  {
    patientId: "patient10",
    doctorId: "doctor2",
    diagnosis: "Cold",
    prescription: "Rest and fluids",
    date: "2024-08-18",
  },
  {
    patientId: "patient10",
    doctorId: "doctor1",
    diagnosis: "Routine Checkup",
    prescription: "Healthy diet",
    date: "2024-09-15",
  },
];

const appointments = [
  {
    patientId: "patient1",
    doctorId: "doctor1",
    date: "2024-09-01",
    status: "accepted",
  },
  {
    patientId: "patient1",
    doctorId: "doctor2",
    date: "2024-09-15",
    status: "pending",
  },
  {
    patientId: "patient1",
    doctorId: "doctor1",
    date: "2024-09-20",
    status: "rejected",
  },
  {
    patientId: "patient2",
    doctorId: "doctor2",
    date: "2024-09-03",
    status: "pending",
  },
  {
    patientId: "patient2",
    doctorId: "doctor1",
    date: "2024-09-10",
    status: "accepted",
  },
  {
    patientId: "patient2",
    doctorId: "doctor2",
    date: "2024-09-25",
    status: "accepted",
  },
  {
    patientId: "patient3",
    doctorId: "doctor1",
    date: "2024-09-12",
    status: "accepted",
  },
  {
    patientId: "patient3",
    doctorId: "doctor2",
    date: "2024-09-18",
    status: "rejected",
  },
  {
    patientId: "patient3",
    doctorId: "doctor1",
    date: "2024-09-30",
    status: "pending",
  },
  {
    patientId: "patient4",
    doctorId: "doctor2",
    date: "2024-09-05",
    status: "accepted",
  },
  {
    patientId: "patient4",
    doctorId: "doctor1",
    date: "2024-09-15",
    status: "pending",
  },
  {
    patientId: "patient4",
    doctorId: "doctor2",
    date: "2024-09-20",
    status: "rejected",
  },
  {
    patientId: "patient5",
    doctorId: "doctor1",
    date: "2024-09-10",
    status: "accepted",
  },
  {
    patientId: "patient5",
    doctorId: "doctor2",
    date: "2024-09-15",
    status: "pending",
  },
  {
    patientId: "patient5",
    doctorId: "doctor1",
    date: "2024-09-25",
    status: "rejected",
  },
  {
    patientId: "patient6",
    doctorId: "doctor1",
    date: "2024-09-02",
    status: "pending",
  },
  {
    patientId: "patient6",
    doctorId: "doctor2",
    date: "2024-09-07",
    status: "accepted",
  },
  {
    patientId: "patient6",
    doctorId: "doctor1",
    date: "2024-09-12",
    status: "rejected",
  },
  {
    patientId: "patient7",
    doctorId: "doctor2",
    date: "2024-09-03",
    status: "accepted",
  },
  {
    patientId: "patient7",
    doctorId: "doctor1",
    date: "2024-09-08",
    status: "pending",
  },
  {
    patientId: "patient7",
    doctorId: "doctor2",
    date: "2024-09-15",
    status: "rejected",
  },
  {
    patientId: "patient8",
    doctorId: "doctor1",
    date: "2024-09-01",
    status: "accepted",
  },
  {
    patientId: "patient8",
    doctorId: "doctor2",
    date: "2024-09-05",
    status: "pending",
  },
  {
    patientId: "patient8",
    doctorId: "doctor1",
    date: "2024-09-12",
    status: "rejected",
  },
  {
    patientId: "patient9",
    doctorId: "doctor2",
    date: "2024-09-10",
    status: "accepted",
  },
  {
    patientId: "patient9",
    doctorId: "doctor1",
    date: "2024-09-15",
    status: "pending",
  },
  {
    patientId: "patient9",
    doctorId: "doctor2",
    date: "2024-09-20",
    status: "rejected",
  },
  {
    patientId: "patient10",
    doctorId: "doctor1",
    date: "2024-09-05",
    status: "accepted",
  },
  {
    patientId: "patient10",
    doctorId: "doctor2",
    date: "2024-09-12",
    status: "pending",
  },
  {
    patientId: "patient10",
    doctorId: "doctor1",
    date: "2024-09-25",
    status: "rejected",
  },
];
